# Generated by Django 4.2.17 on 2024-12-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Bookmarked_Blogs',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='Server.blog'),
        ),
        migrations.AddField(
            model_name='user',
            name='Following',
            field=models.ManyToManyField(blank=True, related_name='Followers', to='Server.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='Liked_Blogs',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='Server.blog'),
        ),
    ]
