# Generated by Django 4.2.17 on 2024-12-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_user_bookmarked_blogs_user_following_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_Name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Tags',
        ),
        migrations.AddField(
            model_name='blog',
            name='Tags',
            field=models.ManyToManyField(blank=True, related_name='Tags', to='Server.tag'),
        ),
    ]
